export const districtData = [
  {
    districtName: "East Kameng",
    hmtCount: 1,
    nurseryCount: 18,
    plantCount: 500,
  },
  {
    districtName: "Papum Pare",
    hmtCount: 1,
    nurseryCount: 15,
    plantCount: 500,
  },
  {
    districtName: "Lower Subansiri",
    hmtCount: 1,
    nurseryCount: 10,
    plantCount: 500,
  },
  {
    districtName: "East Siang",
    hmtCount: 1,
    nurseryCount: 13,
    plantCount: 300,
  },
  {
    districtName: "Lower Dibang Valley",
    hmtCount: 1,
    nurseryCount: 11,
    plantCount: 500,
  },
  {
    districtName: "Anjaw",
    hmtCount: 1,
    nurseryCount: 10,
    plantCount: 500,
  },
  {
    districtName: "Namsai",
    hmtCount: 1,
    nurseryCount: 12,
    plantCount: 500,
  },
  {
    districtName: "Changlang",
    hmtCount: 1,
    nurseryCount: 26,
    plantCount: 500,
  },
  {
    districtName: "Siang",
    hmtCount: 1,
    nurseryCount: 15,
    plantCount: 500,
  },
  {
    districtName: "Siang",
    hmtCount: 1,
    nurseryCount: 18,
    plantCount: 500,
  },
  {
    districtName: "Longding",
    hmtCount: 1,
    nurseryCount: 11,
    plantCount: 300,
  },
  {
    districtName: "Upper Siang",
    hmtCount: 1,
    nurseryCount: 16,
    plantCount: 500,
  },
  {
    districtName: "Leparada",
    hmtCount: 1,
    nurseryCount: 20,
    plantCount: 400,
  },
  {
    districtName: "Dibang Valley",
    hmtCount: 1,
    nurseryCount: 15,
    plantCount: 500,
  },
  {
    districtName: "Lower Siang",
    hmtCount: 1,
    nurseryCount: 18,
    plantCount: 500,
  },
  {
    districtName: "Kamle",
    hmtCount: 1,
    nurseryCount: 18,
    plantCount: 500,
  },
  {
    districtName: "Tawang",
    hmtCount: 1,
    nurseryCount: 17,
    plantCount: 500,
  },
  {
    districtName: "West Kameng",
    hmtCount: 1,
    nurseryCount: 15,
    plantCount: 500,
  },
  {
    districtName: "Kurung Kumey",
    hmtCount: 1,
    nurseryCount: 14,
    plantCount: 400,
  },
  {
    districtName: "Kra Daadi",
    hmtCount: 1,
    nurseryCount: 12,
    plantCount: 400,
  },
];
export const nurseryData = [
  {
    nurseryName: "Green Valley Nursery",
    nurseryMobile: "9876543210",
    TotalPlantName: "5",
    totalPlant: "200",
    nurseryArea: "3 acres",
  },
  {
    nurseryName: "Sunrise Plants",
    nurseryMobile: "9123456789",
    TotalPlantName: "10",
    totalPlant: "500",
    nurseryArea: "5 acres",
  },
  {
    nurseryName: "Eco Flora",
    nurseryMobile: "8765432109",
    TotalPlantName: "0",
    totalPlant: "0",
    nurseryArea: "2 acres",
  },
  {
    nurseryName: "Green Thumb",
    nurseryMobile: "8912345670",
    TotalPlantName: "7",
    totalPlant: "350",
    nurseryArea: "4 acres",
  },
  {
    nurseryName: "Nature's Way",
    nurseryMobile: "7890123456",
    TotalPlantName: "12",
    totalPlant: "600",
    nurseryArea: "6 acres",
  },
];
export const plantData = [
  {
    plantName: "Rose",
    plantVariety: "Hybrid Tea",
    fpoCount: "5",
    plantCount: "200",
  },
  {
    plantName: "Tulip",
    plantVariety: "Darwin Hybrid",
    fpoCount: "0",
    plantCount: "0",
  },
  {
    plantName: "Orchid",
    plantVariety: "Phalaenopsis",
    fpoCount: "3",
    plantCount: "150",
  },
  {
    plantName: "Lily",
    plantVariety: "Asiatic",
    fpoCount: "2",
    plantCount: "75",
  },
  {
    plantName: "Sunflower",
    plantVariety: "Russian Giant",
    fpoCount: "7",
    plantCount: "300",
  },
  {
    plantName: "Sunflower",
    plantVariety: "Russian Giant",
    fpoCount: "7",
    plantCount: "300",
  },
];
export const nurseryDataVisitApprove = [
  {
    id: 1,
    nursery: "Green Valley Nursery",
    address: "123 Green St, Springfield",
    plantName: "Rose",
    varietyOfPlants: "Hybrid Tea",
    plantsQuantity: "150",
    status: "Pending",
    fieldVisit: "Scheduled",
  },
  {
    id: 2,
    nursery: "Sunrise Plants",
    address: "45 Flower Ave, Westfield",
    plantName: "Tulip",
    varietyOfPlants: "Darwin Hybrid",
    plantsQuantity: "80",
    status: "Approved",
    fieldVisit: "Completed",
  },
  {
    id: 4,
    nursery: "Green Thumb",
    address: "89 Plant Ln, Bloomfield",
    plantName: "Lily",
    varietyOfPlants: "Asiatic",
    plantsQuantity: "100",
    status: "Pending",
    fieldVisit: "Scheduled",
  },
  {
    id: 5,
    nursery: "Nature's Way",
    address: "101 Garden St, Sunnyvale",
    plantName: "Sunflower",
    varietyOfPlants: "Russian Giant",
    plantsQuantity: "200",
    status: "Approved",
    fieldVisit: "Completed",
  },
];
