export const StaticStateData = [
  {
    StateName: "Arunachal Pradesh",
    landArea: 9300,
    districtCount: 20,
    farmerCount: 7517,
    figCount: 293,
    fpoCount: 20,
  },
  {
    StateName: "Manipur",
    landArea: 24750,
    districtCount: 18,
    farmerCount: 24750,
    figCount: 1054,
    fpoCount: 50,
  },
];
export const ArunachalPradesh = [
  {
    DistrictName: "East Kameng",
    fpoCount: 1,
    figCount: 18,
    landArea: 500,
    farmerCount: 377,
  },
  {
    DistrictName: "Papum Pare",
    fpoCount: 1,
    figCount: 15,
    landArea: 500,
    farmerCount: 376,
  },
  {
    DistrictName: "Lower Subansiri",
    fpoCount: 1,
    figCount: 10,
    landArea: 500,
    farmerCount: 380,
  },
  {
    DistrictName: "East Siang",
    fpoCount: 1,
    figCount: 13,
    landArea: 300,
    farmerCount: 262,
  },
  {
    DistrictName: "Lower Dibang Valley",
    fpoCount: 1,
    figCount: 11,
    landArea: 500,
    farmerCount: 388,
  },
  {
    DistrictName: "Anjaw",
    fpoCount: 1,
    figCount: 10,
    landArea: 500,
    farmerCount: 350,
  },
  {
    DistrictName: "Namsai",
    fpoCount: 1,
    figCount: 12,
    landArea: 500,
    farmerCount: 280,
  },
  {
    DistrictName: "Changlang",
    fpoCount: 1,
    figCount: 26,
    landArea: 500,
    farmerCount: 457,
  },
  {
    DistrictName: "Siang",
    fpoCount: 1,
    figCount: 15,
    landArea: 500,
    farmerCount: 394,
  },
  {
    DistrictName: "Siang",
    fpoCount: 1,
    figCount: 18,
    landArea: 500,
    farmerCount: 428,
  },
  {
    DistrictName: "Longding",
    fpoCount: 1,
    figCount: 11,
    landArea: 300,
    farmerCount: 373,
  },
  {
    DistrictName: "Upper Siang",
    fpoCount: 1,
    figCount: 16,
    landArea: 500,
    farmerCount: 382,
  },
  {
    DistrictName: "Leparada",
    fpoCount: 1,
    figCount: 20,
    landArea: 400,
    farmerCount: 392,
  },
  {
    DistrictName: "Dibang Valley",
    fpoCount: 1,
    figCount: 15,
    landArea: 500,
    farmerCount: 390,
  },
  {
    DistrictName: "Lower Siang",
    fpoCount: 1,
    figCount: 18,
    landArea: 500,
    farmerCount: 377,
  },
  {
    DistrictName: "Kamle",
    fpoCount: 1,
    figCount: 18,
    landArea: 500,
    farmerCount: 395,
  },
  {
    DistrictName: "Tawang",
    fpoCount: 1,
    figCount: 17,
    landArea: 500,
    farmerCount: 388,
  },
  {
    DistrictName: "West Kameng",
    fpoCount: 1,
    figCount: 15,
    landArea: 500,
    farmerCount: 347,
  },
  {
    DistrictName: "Kurung Kumey",
    fpoCount: 1,
    figCount: 14,
    landArea: 400,
    farmerCount: 396,
  },
  {
    DistrictName: "Kra Daadi",
    fpoCount: 1,
    figCount: 12,
    landArea: 400,
    farmerCount: 385,
  },
];
export const ManiPur = [
  {
    DistrictName: "Bishnupur",
    fpoCount: 1,
    figCount: 16,
    landArea: 400,
    farmerCount: 400,
  },
  {
    DistrictName: "Chandel",
    fpoCount: 5,
    figCount: 114,
    landArea: 2250,
    farmerCount: 2250,
  },
  {
    DistrictName: "Churachandpur",
    fpoCount: 5,
    figCount: 100,
    landArea: 2500,
    farmerCount: 2500,
  },
  {
    DistrictName: "Imphal East",
    fpoCount: 5,
    figCount: 96,
    landArea: 2400,
    farmerCount: 2400,
  },
  {
    DistrictName: "Imphal West",
    fpoCount: 2,
    figCount: 40,
    landArea: 1000,
    farmerCount: 1000,
  },
  {
    DistrictName: "Jiribam",
    fpoCount: 1,
    figCount: 20,
    landArea: 500,
    farmerCount: 500,
  },
  {
    DistrictName: "Kakching",
    fpoCount: 1,
    figCount: 20,
    landArea: 500,
    farmerCount: 500,
  },
  {
    DistrictName: "Kamjong",
    fpoCount: 1,
    figCount: 25,
    landArea: 525,
    farmerCount: 525,
  },
  {
    DistrictName: "Kangpokpi",
    fpoCount: 6,
    figCount: 131,
    landArea: 3275,
    farmerCount: 3275,
  },
  {
    DistrictName: "Khousabung, Churachandpur",
    fpoCount: 1,
    figCount: 20,
    landArea: 500,
    farmerCount: 500,
  },
  {
    DistrictName: "Noney",
    fpoCount: 3,
    figCount: 60,
    landArea: 1300,
    farmerCount: 1300,
  },
  {
    DistrictName: "Pherzawl",
    fpoCount: 4,
    figCount: 80,
    landArea: 2000,
    farmerCount: 2000,
  },
  {
    DistrictName: "Rengkai, Churachandpur",
    fpoCount: 1,
    figCount: 20,
    landArea: 500,
    farmerCount: 500,
  },
  {
    DistrictName: "Senapati",
    fpoCount: 4,
    figCount: 85,
    landArea: 2100,
    farmerCount: 2100,
  },
  {
    DistrictName: "Tamenglong",
    fpoCount: 3,
    figCount: 75,
    landArea: 1500,
    farmerCount: 1500,
  },
  {
    DistrictName: "Tengnoupal",
    fpoCount: 1,
    figCount: 20,
    landArea: 500,
    farmerCount: 500,
  },
  {
    DistrictName: "Thoubal",
    fpoCount: 2,
    figCount: 40,
    landArea: 1000,
    farmerCount: 1000,
  },
  {
    DistrictName: "Ukhrul",
    fpoCount: 4,
    figCount: 92,
    landArea: 2000,
    farmerCount: 2000,
  },
];
